baseapp/controllers/user/views.py
# -*- coding: utf-8 -*-
from flask import (Blueprint, render_template, request, flash,
                   session, redirect, url_for)
from flask.ext.login import login_user, login_required, logout_user, current_user

from .forms import LoginForm, ForgotForm, RegisterForm
from .models import User
from ...utilities import flash_errors
from ...extensions import login_manager

blueprint = Blueprint('user', __name__, url_prefix='/user',
                      static_folder='../static',
                      template_folder='templates')


@login_manager.user_loader
def load_user(user_id):
    uuser = User.search(user_id=int(user_id))
    return uuser

################################################################################
####           Routes                                                       ####
################################################################################

@blueprint.route("/", methods=["GET", "POST"])
def login():
    form = LoginForm(request.form)
    # Handle logging in
    if request.method == 'POST':
        if not form.validate_on_submit():
            flash_errors(form)
            return render_template("login.html", form=form)
        # user password validation done in WTForm
        login_user(form.user)
        form.user.authenticate(is_authentic=True)
        flash("You are logged in.", 'success')
        session['user_id'] = form.user.id
        return form.redirect(url_for('user.login'))

    return render_template("login.html", form=form)


@blueprint.route('/logout')
@login_required
def logout():
    current_user.authenticate(is_authentic=False)
    logout_user()
    flash('You are logged out.', 'info')
    return redirect(url_for('baseapp.home'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        new_user = User.create(username=form.username.data,
                               email=form.email.data,
                               password=form.password.data,
                               active=False) # Gotta be confirmed.
        flash('Thanks for registering. You may be confirmed later.', 'success')
        return redirect(url_for('baseapp.home'))
    else:
        flash_errors(form)
    return render_template('register.html', form=form)


@blueprint.route('/forgot')
def forgot():
    form = ForgotForm(request.form)
    return render_template('forgot.html', form=form)

baseapp/controllers/user/templates/forgot.html
{% extends 'user_skeleton.html' %}
{% block title %}Reset Password{% endblock %}
{% block loginout %}
    <form method="post" class="form form-reset">
      {{ form.hidden_tag() }}
      <h3 class="form-heading">Reset Password <a href="/" title="Back to homepage"><i class="fa fa-home pull-right"></i></a></h3>
      {{ form.email(class_ = 'form-control first-input last-input', placeholder = form.email.label.text) }}
      <p class="pull-left"><a href="{{ url_for('user.login') }}">Login</a></p>
      <p class="pull-right"><a href="{{ url_for('user.register') }}">Register</a></p>
      <input type="submit" value="Submit" class="btn btn-lg btn-primary btn-block">
      <br>
    </form>
{% endblock loginout %}

baseapp/controllers/user/templates/login.html
{% extends 'user_skeleton.html' %}
{% block title %}Login{% endblock %}
{% block loginout %}
    <form method="post" class="form">
      {{ form.hidden_tag() }}
      <h3 class="form-heading">Login <a href="/" title="Back to homepage"><i class="fa fa-home pull-right"></i></a></h3>
      {{ form.username(class_='form-control first-input', placeholder=form.username.label.text, required=true, autofocus=true) }}
      {{ form.password(class_='form-control last-input', placeholder=form.password.label.text, required=true) }}
      <p class="pull-left"><a href="{{ url_for('user.forgot') }}">Forgot Password?</a></p>
      <p class="pull-right"><a href="{{ url_for('user.register') }}">Register</a></p>
      <input type="submit" value="Submit" class="btn btn-primary btn-lg btn-block">
      <br>
    </form>
{% endblock loginout %}

baseapp/controllers/user/templates/register.html
{% extends 'user_skeleton.html' %}
{% block title %}Register{% endblock %}
{% block loginout %}
    <form method="post" class="form">
      {{ form.hidden_tag() }}
      <h3 class="form-heading">Register <a href="/" title="Back to homepage"><i class="fa fa-home pull-right"></i></a></h3>
      {{ form.username(class_ = 'form-control first-input', placeholder = form.username.label.text, required = true, autofocus = true) }}
      {{ form.email(class_ = 'form-control', placeholder = form.email.label.text, required = true) }}
      {{ form.password(class_ = 'form-control', placeholder = form.password.label.text, required = true) }}
      {{ form.confirm(class_ = 'form-control last-input', placeholder = form.confirm.label.text, required = true) }}
      <center><p>Already registered? <a href="{{ url_for('user.login') }}">Login</a></p></center>
      <input type="submit" value="Register" class="btn btn-primary btn-lg btn-block">
      <br>
    </form>
{% endblock loginout %}

baseapp/controllers/user/templates/user_skeleton.html
{% extends 'layouts/skeleton.html' %}
{% block content %}
<div class="container">

  <div class="container col-md-4 col-md-offset-4">
    {% block loginout %}{% endblock loginout %}
  </div>

</div>
{% endblock content %}