baseapp/controllers/user/views.py
# -*- coding: utf-8 -*-
from flask import (Blueprint, render_template, request, flash,
                   session, redirect, url_for)
from flask.ext.login import login_user, login_required, logout_user, current_user

from .forms import LoginForm, ForgotForm, RegisterForm
from .models import User
from ...utilities import flash_errors
from ...extensions import login_manager

blueprint = Blueprint('user', __name__, url_prefix='/user',
                      static_folder='../static',
                      template_folder='templates')


@login_manager.user_loader
def load_user(user_id):
    uuser = User.search(user_id=int(user_id))
    return uuser

################################################################################
####           Routes                                                       ####
################################################################################

@blueprint.route("/", methods=["GET", "POST"])
def login():
    form = LoginForm(request.form)
    # Handle logging in
    if request.method == 'POST':
        if not form.validate_on_submit():
            flash_errors(form)
            return render_template("login.html", form=form)
        # user password validation done in WTForm
        login_user(form.user)
        form.user.authenticate(is_authentic=True)
        flash("You are logged in.", 'success')
        session['user_id'] = form.user.id
        return form.redirect(url_for('user.login'))

    return render_template("login.html", form=form)


@blueprint.route('/logout')
@login_required
def logout():
    current_user.authenticate(is_authentic=False)
    logout_user()
    flash('You are logged out.', 'info')
    return redirect(url_for('baseapp.home'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        new_user = User.create(username=form.username.data,
                               email=form.email.data,
                               password=form.password.data,
                               active=False) # Gotta be confirmed.
        flash('Thanks for registering. You may be confirmed later.', 'success')
        return redirect(url_for('baseapp.home'))
    else:
        flash_errors(form)
    return render_template('register.html', form=form)


@blueprint.route('/forgot')
def forgot():
    form = ForgotForm(request.form)
    return render_template('forgot.html', form=form)

baseapp/templates/layouts/skeleton.html
<!doctype html>
<html class="no-js">
<head>
<meta charset="utf-8">
<title>{% block title %}{{ config.SITE_NAME | default("Flask") }}{% endblock %}</title>

<!-- meta -->
<meta name="description" content="{{ config.SITE_DESCRIPTION | default("") }}">
<meta name="author" content="{{ config.SITE_AUTHOR | default("") }}">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- /meta -->

<!-- styles -->
{% if config.USE_CDN %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto">
{% else %}
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='bower/font-awesome/css/font-awesome.min.css') }}" />
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='bower/bootstrap/dist/css/bootstrap.min.css') }}">
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='bower/bootstrap/dist/css/bootstrap-theme.min.css') }}" />
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='bower/roboto-fontface/css/roboto-fontface.css') }}" />
{% endif %}
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/main.responsive.css') }}" />
<!--[if lt IE 9]><script src="{{ url_for('static', filename='bower/respond/dest/respond.min.js') }}"></script><![endif]-->
<!-- /styles -->

<!-- favicons -->
{% include "snippets/favicons.html" %}
<!-- /favicons -->

<!-- scripts -->
<script src="{{ url_for('static', filename='js/modernizr-custom-2.8.3.min.js') }}"></script>
<!-- /scripts -->
{% block head %}{% endblock head %}
</head>
<body>

  <!-- Wrap all page content here -->
  <div id="wrap">

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('baseapp.home') }}">{{ config.SITE_NAME |d("Flask Website") }}</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% if header_links %}
            {% for name,route in header_links %}
              <li><a href="{{ url_for(route) }}">{{ name }}</a></li>
            {% endfor %}
            {% endif %}
          </ul>
          <ul class="nav navbar-nav pull-right">
          {% if current_user %}
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown">User <b class="caret"></b></a>
              <ul class="dropdown-menu">
              {% if not current_user.is_authenticated() %}
                <li><a href="{{ url_for('user.login') }}">Login</a></li>
                <li><a href="{{ url_for('user.register') }}">Register</a></li>
              {% else %}
                <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
              {% endif %}
              </ul>
            </li>
          {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- Begin page content -->
    <main id="content" role="main" class="container">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-block alert-warning fade in">
              <a class="close" data-dismiss="alert">&times;</a>
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      {% block content %}{% endblock %}

    </main>

  </div>

  <div id="footer">
    <div class="container">
      <br>
      <p>{% if config.DEBUG %}<strong>(DEBUG MODE ON)</strong>{% endif %}
         {{ config.SITE_AUTHOR | default("") }} &copy; All Rights Reserved.</p>
      {% block footer %}{% endblock %}
    </div>
  </div>

  {% if config.USE_CDN %}
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="{{ url_for('static', filename='bower/jquery/dist/jquery.min.js') }}"><\/script>')</script>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  {% else %}
  <script src="{{ url_for('static', filename='bower/jquery/dist/jquery.min.js') }}"></script>
  <script defer src="{{ url_for('static', filename='bower/bootstrap/dist/js/bootstrap.min.js') }}"></script>

  <script defer src="{{ url_for('static', filename='js/main.js') }}"></script>
  {% endif %}
  {% if config.GOOGLE_ANALYTICS %}
  <!-- Google Analytics -->
  <script>
  window._gaq = [['_setAccount','{{ config.GOOGLE_ANALYTICS | default("") }}'],['_trackPageview'],['_trackPageLoadTime']];
  Modernizr.load({
    load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
  });
  </script>
  {% endif %}

  {% block endofpage %}{% endblock endofpage %}
</body>
</html>